In [1]:
import numpy as np

In [2]:
A = np.matrix([
    [0, 1, 0, 0],
    [0, 0, 1, 1], 
    [0, 1, 0, 0],
    [1, 0, 1, 0]],
    dtype=float)

X = np.matrix([[i] for i in range(A.shape[0])], dtype=float)
X

matrix([[0.],
        [1.],
        [2.],
        [3.]])

In [3]:
A@X

matrix([[1.],
        [5.],
        [1.],
        [2.]])

matrix([[0.],
        [1.],
        [2.],
        [3.]])

In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as Fun
word_conversion = {"hey": 0, "there": 1}
embeddings = nn.Embedding(2, 3)
lookup = torch.tensor([word_conversion["hey"]], dtype=torch.long)
hey_embeddings = embeddings(lookup)
print(hey_embeddings)

tensor([[-0.4791, -0.9889,  0.3013]], grad_fn=<EmbeddingBackward0>)
